# Generated by Django 5.1.6 on 2025-04-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_options_alter_posts_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
